export enum ErrorCode {
  // Validation errors
  FILE_NAME_REQUIRED = 'FILE_NAME_REQUIRED',
  OWNER_ID_REQUIRED = 'OWNER_ID_REQUIRED',
  CONTENT_TYPE_REQUIRED = 'CONTENT_TYPE_REQUIRED',
  FILE_FORMAT_REQUIRED = 'FILE_FORMAT_REQUIRED',
  FILE_FORMAT_INVALID = 'FILE_FORMAT_INVALID',
  FILE_SIZE_INVALID = 'FILE_SIZE_INVALID',
  STORAGE_PATH_REQUIRED = 'STORAGE_PATH_REQUIRED',
  FOLDER_NAME_REQUIRED = 'FOLDER_NAME_REQUIRED',
  PARENT_ID_REQUIRED = 'PARENT_ID_REQUIRED',
  INVALID_STRING = 'INVALID_STRING',
  INVALID_BOOLEAN = 'INVALID_BOOLEAN',
  INVALID_ENUM = 'INVALID_ENUM',
  INVALID_NUMBER = 'INVALID_NUMBER',
  FILE_TYPE_INVALID = 'FILE_TYPE_INVALID',
  FILE_KEY_REQUIRED = 'FILE_KEY_REQUIRED',

  PAGE_SIZE_INVALID = 'PAGE_SIZE_INVALID',
  PAGE_INVALID = 'PAGE_INVALID',

  // Business logic errors
  INVALID_PARENT_FOLDER = 'INVALID_PARENT_FOLDER',
  FILE_ALREADY_EXISTS = 'FILE_ALREADY_EXISTS',
  FOLDER_ALREADY_EXISTS = 'FOLDER_ALREADY_EXISTS',
  RESOURCE_TRASHED = 'RESOURCE_TRASHED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  FOLDER_NOT_FOUND = 'FOLDER_NOT_FOUND',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  PARENT_FOLDER_TRASHED = 'PARENT_FOLDER_TRASHED',
  FOLDER_TRASHED = 'FOLDER_TRASHED',
  FILE_TRASHED = 'FILE_TRASHED',
  FILE_KEY_INVALID = 'FILE_KEY_INVALID',
  INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE',

  // Database errors
  FOREIGN_KEY_CONSTRAINT = 'FOREIGN_KEY_CONSTRAINT',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',

  // Generic errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  INVALID_EMAIL = 'INVALID_EMAIL',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_AGE = 'INVALID_AGE',
  REQUIRED_FIELD = 'REQUIRED_FIELD',

  // Not found errors
  NOT_FOUND = 'NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  POST_NOT_FOUND = 'POST_NOT_FOUND',

  // Conflict errors
  CONFLICT = 'CONFLICT',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',

  // Server errors
  DATABASE_ERROR = 'DATABASE_ERROR',

  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  INVALID_TOKEN = 'INVALID_TOKEN',

  BAD_REQUEST = 'BAD_REQUEST',
  INVALID_INPUT = 'INVALID_INPUT',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Database errors
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  DATABASE_UNAVAILABLE = 'DATABASE_UNAVAILABLE',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
}
