export enum ContentType {
  FOLDER = 'folder',
  PDF = 'application/pdf',
  JPEG = 'image/jpeg',
  JPG = 'image/jpg',
  PNG = 'image/png',
  GIF = 'image/gif',
  SVG = 'image/svg+xml',
  MP4 = 'video/mp4',
  WEBM = 'video/webm',
  OGG = 'video/ogg',
  WAV = 'audio/wav',
  MP3 = 'audio/mpeg',
  JSON = 'application/json',
  XML = 'application/xml',
  TXT = 'text/plain',
  xls = 'application/vnd.ms-excel',
  xlsx = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  DOC = 'application/msword',
  DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  PPT = 'application/vnd.ms-powerpoint',
  PPTX = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  CSV = 'text/csv',
  ZIP = 'application/zip',
}

export const MimeTypes: Record<string, string> = {
  // Images
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  gif: 'image/gif',
  webp: 'image/webp',
  svg: 'image/svg+xml',
  bmp: 'image/bmp',
  ico: 'image/x-icon',
  tiff: 'image/tiff',
  tif: 'image/tiff',
  avif: 'image/avif',
  heic: 'image/heic',
  heif: 'image/heif',

  // Documents
  pdf: 'application/pdf',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ppt: 'application/vnd.ms-powerpoint',
  pptx: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  odt: 'application/vnd.oasis.opendocument.text',
  ods: 'application/vnd.oasis.opendocument.spreadsheet',
  odp: 'application/vnd.oasis.opendocument.presentation',
  rtf: 'application/rtf',
  pages: 'application/vnd.apple.pages',
  numbers: 'application/vnd.apple.numbers',
  keynote: 'application/vnd.apple.keynote',

  // Text
  txt: 'text/plain',
  csv: 'text/csv',
  tsv: 'text/tab-separated-values',
  html: 'text/html',
  htm: 'text/html',
  css: 'text/css',
  js: 'text/javascript',
  json: 'application/json',
  xml: 'application/xml',
  yaml: 'text/yaml',
  yml: 'text/yaml',
  md: 'text/markdown',
  markdown: 'text/markdown',
  log: 'text/plain',
  conf: 'text/plain',
  cfg: 'text/plain',
  ini: 'text/plain',

  // Programming Languages
  py: 'text/x-python',
  java: 'text/x-java-source',
  c: 'text/x-c',
  cpp: 'text/x-c++',
  h: 'text/x-c',
  hpp: 'text/x-c++',
  cs: 'text/x-csharp',
  php: 'text/x-php',
  rb: 'text/x-ruby',
  go: 'text/x-go',
  rs: 'text/x-rust',
  swift: 'text/x-swift',
  kt: 'text/x-kotlin',
  scala: 'text/x-scala',
  sh: 'application/x-sh',
  bash: 'application/x-sh',
  zsh: 'application/x-sh',
  fish: 'application/x-sh',
  ps1: 'application/x-powershell',
  bat: 'application/x-bat',
  cmd: 'application/x-bat',
  sql: 'application/sql',
  r: 'text/x-r',
  pl: 'text/x-perl',
  lua: 'text/x-lua',
  dart: 'text/x-dart',
  ts: 'text/typescript',
  tsx: 'text/typescript',
  jsx: 'text/javascript',
  vue: 'text/x-vue',
  svelte: 'text/x-svelte',

  // Archives
  zip: 'application/zip',
  rar: 'application/vnd.rar',
  '7z': 'application/x-7z-compressed',
  tar: 'application/x-tar',
  gz: 'application/gzip',
  bz2: 'application/x-bzip2',
  xz: 'application/x-xz',
  iso: 'application/x-iso9660-image',

  // Audio
  mp3: 'audio/mpeg',
  wav: 'audio/wav',
  flac: 'audio/flac',
  aac: 'audio/aac',
  ogg: 'audio/ogg',
  wma: 'audio/x-ms-wma',
  m4a: 'audio/mp4',
  aiff: 'audio/aiff',
  au: 'audio/basic',
  mid: 'audio/midi',
  midi: 'audio/midi',
  opus: 'audio/opus',
  webm: 'audio/webm',

  // Video
  mp4: 'video/mp4',
  avi: 'video/x-msvideo',
  mov: 'video/quicktime',
  wmv: 'video/x-ms-wmv',
  flv: 'video/x-flv',
  mkv: 'video/x-matroska',
  m4v: 'video/mp4',
  '3gp': 'video/3gpp',
  '3g2': 'video/3gpp2',
  mpg: 'video/mpeg',
  mpeg: 'video/mpeg',
  ogv: 'video/ogg',
  mts: 'video/mp2t',
  asf: 'video/x-ms-asf',
  rm: 'application/vnd.rn-realmedia',
  rmvb: 'application/vnd.rn-realmedia-vbr',

  // Fonts
  ttf: 'font/ttf',
  otf: 'font/otf',
  woff: 'font/woff',
  woff2: 'font/woff2',
  eot: 'application/vnd.ms-fontobject',

  // CAD/Design
  dwg: 'application/acad',
  dxf: 'application/dxf',
  step: 'application/step',
  stp: 'application/step',
  iges: 'application/iges',
  igs: 'application/iges',
  stl: 'application/vnd.ms-pki.stl',
  obj: 'application/x-tgif',
  '3ds': 'application/x-3ds',
  blend: 'application/x-blender',
  skp: 'application/vnd.sketchup.skp',

  // Adobe
  ai: 'application/illustrator',
  psd: 'application/x-photoshop',
  indd: 'application/x-indesign',
  eps: 'application/postscript',
  ps: 'application/postscript',

  // eBooks
  epub: 'application/epub+zip',
  mobi: 'application/x-mobipocket-ebook',
  azw: 'application/vnd.amazon.ebook',
  azw3: 'application/vnd.amazon.ebook',
  fb2: 'application/x-fictionbook+xml',

  // Data/Database
  sqlite: 'application/vnd.sqlite3',
  db: 'application/vnd.sqlite3',
  mdb: 'application/vnd.ms-access',
  accdb: 'application/vnd.ms-access',
  dbf: 'application/vnd.dbf',

  // Virtual Machine/Disk Images
  vmdk: 'application/x-vmdk',
  vdi: 'application/x-virtualbox-vdi',
  qcow2: 'application/x-qemu-disk',
  vhd: 'application/x-vhd',
  vhdx: 'application/x-vhdx',

  // Executables
  exe: 'application/vnd.microsoft.portable-executable',
  msi: 'application/x-msdownload',
  deb: 'application/vnd.debian.binary-package',
  rpm: 'application/x-rpm',
  pkg: 'application/x-newton-compatible-pkg',
  apk: 'application/vnd.android.package-archive',
  ipa: 'application/octet-stream',
  app: 'application/x-executable',
  dmg: 'application/x-apple-diskimage',
  snap: 'application/vnd.snap',
  flatpak: 'application/vnd.flatpak',
  appimage: 'application/x-executable',

  // Configuration/System
  plist: 'application/x-plist',
  reg: 'text/plain',
  service: 'text/plain',
  desktop: 'application/x-desktop',
  dockerfile: 'text/plain',
  vagrantfile: 'text/x-ruby',
  makefile: 'text/x-makefile',
  cmake: 'text/x-cmake',
  gradle: 'text/x-gradle',
  maven: 'application/xml',
  yarn: 'text/yaml',
  lock: 'text/plain',
  env: 'text/plain',
  gitignore: 'text/plain',
  htaccess: 'text/plain',
  eslintrc: 'application/json',
  prettierrc: 'application/json',
  editorconfig: 'text/plain',

  // Certificates/Keys
  pem: 'application/x-pem-file',
  crt: 'application/x-x509-ca-cert',
  cer: 'application/x-x509-ca-cert',
  der: 'application/x-x509-ca-cert',
  p12: 'application/x-pkcs12',
  pfx: 'application/x-pkcs12',
  key: 'application/octet-stream',
  pub: 'text/plain',
  gpg: 'application/pgp-keys',
  asc: 'text/plain',

  // Backup/Logs
  bak: 'application/octet-stream',
  backup: 'application/octet-stream',
  old: 'application/octet-stream',
  tmp: 'application/octet-stream',
  temp: 'application/octet-stream',
  cache: 'application/octet-stream',
  dmp: 'application/octet-stream',
  crash: 'text/plain',
  stackdump: 'text/plain',

  // Scientific/Research
  mat: 'application/matlab-mat',
  fig: 'application/matlab-fig',
  hdf5: 'application/x-hdf',
  h5: 'application/x-hdf',
  nc: 'application/x-netcdf',
  cdf: 'application/x-netcdf',
  fits: 'application/fits',
  fts: 'application/fits',
  root: 'application/x-root',
  nii: 'application/octet-stream',
  dcm: 'application/dicom',
  dicom: 'application/dicom',

  // Game Files
  unity: 'application/octet-stream',
  unitypackage: 'application/octet-stream',
  pak: 'application/octet-stream',
  wad: 'application/octet-stream',
  rom: 'application/octet-stream',
  nds: 'application/octet-stream',
  gba: 'application/octet-stream',
  sav: 'application/octet-stream',

  // Miscellaneous
  torrent: 'application/x-bittorrent',
  magnet: 'application/x-magnet',
  calendar: 'text/calendar',
  ics: 'text/calendar',
  vcf: 'text/vcard',
  vcard: 'text/vcard',
  kml: 'application/vnd.google-earth.kml+xml',
  kmz: 'application/vnd.google-earth.kmz',
  gpx: 'application/gpx+xml',
  rss: 'application/rss+xml',
  atom: 'application/atom+xml',
  opml: 'text/x-opml',
  mbox: 'application/mbox',
  eml: 'message/rfc822',
  msg: 'application/vnd.ms-outlook',
  pst: 'application/vnd.ms-outlook',
  contact: 'text/x-vcard',
  webloc: 'application/x-webloc',
  url: 'application/internet-shortcut',
};

export enum FileFormat {
  PDF = 'pdf',
  JPEG = 'jpeg',
  JPG = 'jpg',
  PNG = 'png',
  GIF = 'gif',
  SVG = 'svg',
  MP4 = 'mp4',
  WEBM = 'webm',
  OGG = 'ogg',
  WAV = 'wav',
  MP3 = 'mp3',
  JSON = 'json',
  XML = 'xml',
  TXT = 'txt',
  xls = 'xls',
  xlsx = 'xlsx',
  DOC = 'doc',
  DOCX = 'docx',
  PPT = 'ppt',
  PPTX = 'pptx',
  CSV = 'csv',
  ZIP = 'zip',
}

export enum FilePermission {
  VIEW = 'view',
  EDIT = 'edit',
  COMMENT = 'comment',
}

export const FOLDER_VIEW_KEY = 'folderView';

export enum FileSortField {
  CREATED_AT = 'createdAt',
  UPDATED_AT = 'updatedAt',
  IS_FOLDER = 'isFolder',
}

export const SYSTEM_FILE = {
  MY_STORAGE: {
    id: 'null',
    name: 'My Storage',
    code: 'MY_STORAGE',
    isSystem: true,
    invalidationKey: 'MY_STORAGE',
  },
  SHARED_WITH_ME: {
    id: 'null',
    name: 'Shared with me',
    code: 'SHARED_WITH_ME',
    isSystem: true,
    invalidationKey: 'SHARED_WITH_ME',
  },
  TRASH: {
    id: 'null',
    name: 'Trash',
    code: 'TRASH',
    system: true,
    invalidationKey: 'TRASH',
  },
} as const;
