export const APP_LOCAL_QUEUES = {
  system: {
    name: 'system-queue',
    jobName: 'system-queue-job',
  },
};

export enum ProcessorAction {
  MOVE_FILE_AFTER_CREATE = 'MOVE_FILE_AFTER_CREATE',
  NESTED_SET_MOVE_NODE = 'NESTED_SET_MOVE_NODE',
  NESTED_SET_DELETE_NODE = 'NESTED_SET_DELETE_NODE',
  NESTED_SET_REBUILD_TREE = 'NESTED_SET_REBUILD_TREE',
  DELETE_FILE_FROM_STORAGE = 'DELETE_FILE_FROM_STORAGE',
}
