export const APP_LOCAL_QUEUES = {
  system: {
    name: 'system-queue',
    jobName: 'system-queue-job',
  },
};

export enum ProcessorAction {
  UPDATE_FILE_TAG_IN_STORAGE = 'UPDATE_FILE_TAG_IN_STORAGE',
  NESTED_SET_MOVE_NODE = 'NESTED_SET_MOVE_NODE',
  NESTED_SET_DELETE_NODE = 'NESTED_SET_DELETE_NODE',
  NESTED_SET_REBUILD_TREE = 'NESTED_SET_REBUILD_TREE',
  DELETE_FILE_FROM_STORAGE = 'DELETE_FILE_FROM_STORAGE',
  DELETE_FILE_AND_CHILDREN_FROM_STORAGE = 'DELETE_FILE_AND_CHILDREN_FROM_STORAGE',
  SEND_EMAIL_NOTIFICATION = 'SEND_EMAIL_NOTIFICATION',
}
