org: rzlab
service: keepcloud-api

custom:
  stage: ${env:STAGE}
  serverless-offline:
    httpPort: 3333
    lambdaPort: 2333
    noPrependStageInUrl: true
  allowedOrigins: ${file(../../sls-helper.js):allowedOrigins}
  domain:
    dev: ${env:STAGE}-keepcloud.api.${env:DOMAIN_NAME}
    production: keepcloud.api.${env:DOMAIN_NAME}
  customDomain:
    domainName: ${self:custom.domain.${env:STAGE}}
    stage: ${env:STAGE}
    certificateName: '*.api.${env:DOMAIN_NAME}'
    securityPolicy: tls_1_0
    createRoute53Record: true
    createRoute53IPv6Record: false
    autoDomain: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-domain-manager

provider:
  name: aws
  stage: ${env:STAGE}
  runtime: nodejs20.x
  region: eu-west-3
  timeout: 900 # in seconds
  memorySize: 1024 # in MB
  versionFunctions: false

  deploymentBucket:
    name: keepcloud.api.deployment
  environment:
    NODE_ENV: ${self:NODE_ENV, 'production'}
    APP_AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    APP_AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    APP_AWS_DEFAULT_REGION: ${env:AWS_DEFAULT_REGION}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
    VITE_GOOGLE_CLIENT_ID: ${env:VITE_GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${env:GOOGLE_CLIENT_SECRET}
    FILE_BUCKET: keepcloud.storage.${env:STAGE}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}
    SYSTEM_QUEUE_URL:
      Ref: SystemQueue
    API_ALLOWED_ORIGIN_LIST: ${env:API_ALLOWED_ORIGIN_LIST}
    DATABASE_URL: ${env:DATABASE_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            Fn::GetAtt:
              - SystemQueue
              - Arn

        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource: arn:aws:s3:::templates.${env:DOMAIN_NAME}

        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: arn:aws:s3:::templates.${env:DOMAIN_NAME}/*

        - Effect: Allow
          Action:
            - s3:ListBucket
          Resource:
            - 'arn:aws:s3:::keepcloud.storage.${env:STAGE}'

        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - 'arn:aws:s3:::keepcloud.storage.${env:STAGE}/*'

        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource:
            - 'arn:aws:ses:us-east-1:*:identity/${env:DOMAIN_NAME}'
package:
  include:
    - ../../dist/apps/api/**
    - ../../node_modules/.prisma/client/**
    - ../../node_modules/@prisma/client/**
    - ../../node_modules/prisma/**
    - ../../node_modules/.cache/prisma/**
  exclude:
    - ./**
  patterns:
    - '!../../node_modules/.prisma/client/libquery_engine-*' # exclude all native engines...
    - '../../node_modules/.prisma/client/libquery_engine-rhel-*' # ...except for Linux x64
    - '!../../node_modules/@prisma/engines/**'
    - '!../../node_modules/.cache/prisma/**'

functions:
  main:
    handler: dist/apps/api/main.handler
    events:
      - http:
          path: /{any+}
          method: ANY
      - sqs:
          arn:
            Fn::GetAtt:
              - SystemQueue
              - Arn

resources:
  Resources:
    FileStorageBucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: keepcloud.storage.${env:STAGE}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - POST
                - GET
              AllowedOrigins: ${self:custom.allowedOrigins}
        LifecycleConfiguration:
          Rules:
            - Id: DeletePendingUploads
              Status: Enabled
              ExpirationInDays: 2
              TagFilters:
                - Key: upload
                  Value: pending

    SystemQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: keepcloud-system-queue-${env:STAGE}.fifo
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 900 # 15 minutes
