name: Deploy API

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      JWT_SECRET:
        required: true
      JWT_REFRESH_SECRET:
        required: true
      GOOGLE_CLIENT_SECRET:
        required: true
      SERVERLESS_ACCESS_KEY:
        required: true
      DATABASE_PASSWORD:
        required: true
      DATABASE_ADMIN_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      STAGE: ${{ vars.STAGE }}

      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

      VITE_GOOGLE_CLIENT_ID: ${{ vars.VITE_GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      DATABASE_URL: postgresql://${{ vars.DATABASE_USERNAME }}:${{ secrets.DATABASE_PASSWORD }}@${{ vars.DATABASE_HOST }}:${{ vars.DATABASE_PORT }}/${{ vars.DATABASE_NAME }}?schema=${{ vars.DATABASE_SCHEMA }}
      DATABASE_ADMIN_URL: postgresql://${{ vars.DATABASE_ADMIN_USERNAME }}:${{ secrets.DATABASE_ADMIN_PASSWORD }}@${{ vars.DATABASE_HOST }}:${{ vars.DATABASE_PORT }}/${{ vars.DATABASE_NAME }}?schema=${{ vars.DATABASE_SCHEMA }}

      SYSTEM_QUEUE_URL: ${{ vars.SYSTEM_QUEUE_URL }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      FILE_BUCKET: keepcloud.storage.${{ vars.STAGE }}
      LOG_LEVEL: info
      API_ALLOWED_ORIGIN_LIST: ${{ vars.API_ALLOWED_ORIGIN_LIST }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      FRONTEND_URL: ${{ vars.FRONTEND_URL }}
      TEMPLATES_BUCKET: ${{ vars.TEMPLATES_BUCKET }}
      SUPPORT_EMAIL: ${{ vars.SUPPORT_EMAIL }}
      NO_REPLY_EMAIL: ${{ vars.NO_REPLY_EMAIL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Generate Prisma client
        run: yarn prisma generate

      - name: Build API
        run: yarn nx run keepcloud-api:build:production

      - name: Deploy API with Serverless
        run: NODE_ENV=production yarn nx run keepcloud-api:deploy

      - name: Run Prisma migrations
        run: yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ env.DATABASE_ADMIN_URL }}

      - name: Seed database
        run: yarn prisma db seed
        env:
          DATABASE_URL: ${{ env.DATABASE_ADMIN_URL }}
