name: KeepCloud Deployment

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - production

jobs:
  web_dev:
    if: |
      (github.ref == 'refs/heads/develop' || github.event.pull_request.base.ref == 'develop') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    uses: ./.github/workflows/deploy-web.yml
    with:
      environment: Dev

  api_dev:
    if: |
      (github.ref == 'refs/heads/develop' || github.event.pull_request.base.ref == 'develop') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: Dev
