name: KeepCloud Deployment

on:
  pull_request:
    types: [closed] # only after merge
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select deployment environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - production

jobs:
  web:
    name: Web (${{ (github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'dev') && 'Dev' || 'Production' }})
    if: |
      github.ref == 'refs/heads/develop' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    uses: ./.github/workflows/deploy-web.yml
    with:
      environment: ${{ (github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'dev') && 'Dev' || 'Production' }}
    secrets: inherit

  api:
    name: API (${{ (github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'dev') && 'Dev' || 'Production' }})
    if: |
      github.ref == 'refs/heads/develop' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    uses: ./.github/workflows/deploy-api.yml
    with:
      environment: ${{ (github.ref == 'refs/heads/develop' || github.event.inputs.environment == 'dev') && 'Dev' || 'Production' }}
    secrets: inherit
